module.exports = {
    common_01: '方法不支持',
    common_api_01: '已经存在',
    common_api_02: '选定项目不存在',
    common_api_03: '文件类型错误',
    api_template_01: '模板不存在',
    domain_01: '组织已存在',
    domain_02: '机构不存在',
    domain_03: '已存在总公司类型机构',
    group_01: '用户组已存在',
    group_02: '用户组不存在',
    group_03: '叶子节点没有路径',
    group_04: '用户组下存在用户',
    group_05: '角色存在',
    usersetting_01: '密码错误',
    usersetting_02: '用户不存在',
    operator_01: '组不存在',
    operator_02: '用户已经存在',
    operator_03: '用户不存在',
    operator_04: '用户下有未完成订单',
    customer_01: '客户组不存在',
    customer_02: '客户已经存在',
    customer_03: '客户不存在',
    customer_04: '手机号已存在',
    order_01: '订单已存在',
    order_02: '订单不存在',
    order_03: '该企业法人预付金以及信用额度不足以支付',
    order_04: '订单未开工',
    order_05: '施工验收项未全部通过',
    nodeState_01: '请分配所有节点',
    crew_01: '工人已存在',
    crew_02: '工人不存在',
    warehouse_01: '仓库信息不存在',
    warehouse_02: '仓库编号已存在',
    wareHouseZone_01: '仓区名已存在',
    wareHouseZone_02: '仓区信息不存在',
    templateConstruction_01: '主计划不存在',
    constructionNode_01: '施工节点不存在',
    acceptance_01: '验收项不存在',
    acceptance_02: '验收项状态不正确',
    acceptance_03: '用户不正确',
    acceptance_04: 'act内容错误',
    acceptance_05: '审核状态不正确',
    orderdetail_01: '订单不存在',
    orderdetail_02: 'check_owner类型错误',
    orderdetail_03: 'check_type类型错误',
    orderdetail_04: 'check_state类型错误',
    orderdetail_05: '空间已存在',
    orderdetail_06: '造艺设计不存在',
    orderdetail_07: '订单评审未完成',
    orderdetail_08: '生成制造单失败',
    orderdetail_09: '请上传设计文档',
    orderdetail_10: '重传制造单失败',
    orderdetail_11: '请先生成施工计划',
    materiel_01: '物料信息不存在',
    materiel_02: '物料编码已存在',
    materiel_03: '该订单下无有效空间',
    materiel_04: '物料管理中无此物料,无法做减项',
    materiel_05: '物料已存在',
    materiel_06: '请指定物料审核人',
    materiel_07: '该物料不属于本机构',
    materiel_08: '请选择空间，然后添加物料',
    design_01: '设计方案不存在',
    measure_01: '量尺信息不存在',
    staff_01: '队员信息不存在',
    staff_02: '该队员已添加',
    file_01: '设计文档不存在',
    vr_01: 'VR效果图不存在',
    check_01: '方案尚未提交审核',
    appointment_01: '预约不存在',
    appointment_02: '24小时内只能预约一次',
    appointment_03: '该房间已存在未完成的订单，不能重复创建',
    menu_01: '菜单已经存在',
    menu_02: '菜单不存在',
    menu_03: '菜单下有子项',
    menu_04: '未配置路径',
    mbap_01: 'domain_id is missing',
    reg_01: 'phone is missing',
    reg_02: 'type is missing',
    reg_03: 'code is missing',
    reg_04: 'password is missing',
    reg_05: 'name is missing',
    auth_01: 'domain is missing',
    auth_02: 'username is missing',
    auth_03: 'identifyCode is missing',
    auth_04: 'magicNo is missing',
    auth_05: '用户不存在或密码错误',
    auth_06: '电话不存在',
    auth_07: '类型不存在',
    auth_08: '发送验证码失败',
    auth_09: '验证码错误',
    auth_10: '用户组不存在',
    auth_11: '用户类型不存在',
    auth_12: '验证码错误',
    auth_13: '请输入正确的手机号码',
    auth_14: '请输入正确的用户类型',
    auth_15: 'type is missing',
    auth_16: 'phone is missing',
    auth_17: 'code is missing',
    auth_18: 'password is missing',
    auth_19: 'loginType is missing',
    exist_01: '编码或者名称已存在',
    template_01: '套餐不存在',
    template_material_01: '空间不能重复',
    change_modify: '修改数量不符合要求，请重新计算',
    plan_01: '施工计划不存在',
    contract_01: '合同不存在',
    receivables_01: '收款记录不存在',
    receivables_02: '还未创建收款项',
    inquiry_01: '询价不存在',
    purchase_01: '采购单不存在',
    whsCode_01: '仓库编码不存在',
    geo_01: '请输入准确的地理信息',
    estate_01: '楼盘不存在',
    estate_02: '该地区已存在相同楼盘',
    room_01: '该房间已经存在',
    room_02: '栋号错误',
    room_03: '单元号错误',
    room_04: '房间号错误',
    room_05: '户型不存在',
    acceptance_plan_01: '未生成施工计划',
    acceptance_plan_02: '未设置空间',
    roomtype_01: '该户型名称已经存在',
    roomtype_02: '该户型不存在',
    purchase_order_01: '该采购单不存在',
    follow_01: '关注审核项不存在',
    puchase_apply_01: '该申请单已经提交',
    puchase_apply_02: '该申请单已经通过',
    puchase_apply_03: '该申请单不存在',
    landagent_01: '地产商信息不存在',
    landagent_02: '当前机构已存在相同的地产商信息',
    check_inventory_01: '盘点计划已存在',
    task_01: '任务不存在',
    task_02: '该任务没有指派审核人',
    complaint_01: '投诉不存在',
    complaint_02: '受理失败',
    produce_01: '产品信息不存在',
    produce_02: '产品计划已经存在',
    produce_03: '产品计划不存在',
    produce_04: '物料不存在',
    produce_05: '风格不存在',
    produce_06: '产品计划没有物料',
    produce_07: '产品计划没有工序',
    produce_08: '产品计划审核已提交',
    produce_09: '产品计划没有配置审核项',
    produce_10: '产品规划未完成评审',
    procedure_01: '生产工序不存在',
    procedure_02: '生产工序已存在',
    productdevice_01: '生产设备已存在',
    require_01: '3D效果只允许有一条',
    require_41: '产品规划评审不存在',
    invalidateApplyorder_01: '报废数量超过库存数量',
    invalidateApplyorder_02: '已存在报废物料',
    stockoutapplydetail_01: '已存在出库物料',
    stockoutapplydetail_02: '该仓区库存不足，请选择其他仓区',
    stockoutapplydetail_03: '请输入出库数量',
    stockoutapplydetail_04: '已出库总数量超出需要数量',
    moving_01: '已超过库存数量',
    moving_02: '请输入大于0的数',
    moving_03: '该物料不存在',
    site_case_01: '案例不存在',
    site_case_02: '案例图片不存在',
    site_diary_01: '日记不存在',
    stock_01: '该物料已超过申请数量',
    stock_02: '请同步安全库存物料',
    stock_03: '请填写数量',
    stock_04: '在您选择的仓区中，该物料没有绑定销售单号',
    stock_05: '物料不足',
    stock_06: '该物料已超过需求数量',
    stock_07: '未找到要入库物料',
    worker_01: '该工种名称已存在',
    worker_02: '该记录不存在',
    worker_03: '不能修改其它机构的信息',
    project_01: '您还有空间没有预算金额',
    project_02: '您还有户型没有决算金额',
    project_03: '您的csv文件内容不完整',
    project_04: '您的csv文件格式不正确',
    project_05: '您还有空间没有物料决算金额',
    notice_01: '通知公告不存在',
    notice_02: '回答错误',
    hr_01: '人力需求信息不存在',
    user_01: '姓名错误',
    user_02: '性别错误',
    user_03: '部门错误',
    user_04: '兼职部门与部门重复',
    user_05: '总机构下无法添加角色',
    user_06: '请选择岗位',
    user_07: '该员工已离职不能绑定酷家乐账号',
    user_08: '请添加该员工报销职级',
    contract_01: '合同已存在',
    contract_02: '合同不存在',
    experience_01: '工作经历已存在',
    experience_02: '工作经历不存在',
    ordershopsync_01: '订单号不存在',
    ordershopsync_02: '物料信息不存在',
    ordershopsync_03: '订单状态不正确',
    ordershopsync_04: 'token不存在',
    quality_01: '未提交要质检的产品',
    quality_02: '提交记录中，待质检数量不能小于合格数量与不合格数量之和',
    quality_03: '请输入数量',
    collecton_01: 'type类型不正确',
    collecton_02: '您已收藏',
    returntask_01: '退货任务没有分配审批人',
    loan_01: '贷款记录不存在',
    loan_02: '该订单您已经申请了贷款',
    foreman_01: '该工长有正在施工中的订单，不能解除绑定',
    meetingroom_01: '会议室不存在',
    meetingroom_02: '会议室已存在',
    meetingroom_03: '该记录已提交',
    meetingEquipment_01: '设备不存在',
    meetingEquipment_02: '设备已存在',
    meetingEquipment_03: '设备已存在在其他会议室',
    vehicle_01: '车辆不存在',
    vehicle_02: '车辆正在使用，无法删除',
    meeting_01: '会议不存在',
    meeting_02: '请填写正确数量',
    meeting_03: '已超过该设备数量',
    meeting_04: '当前会议室已被预订，请选择其他会议室或者修改会议时间再进行预订',
    meeting_05: '该人员已添加',
    meetingAttendee_01: '设备不存在',
    meetingAttendee_02: '人员不存在',
    meetingAttendee_03: '请增加人员',
    meetingFollow_01: '跟进事项不存在',
    trafficApply_01:'申请单不存在',
    trafficApply_02:'该时间段内车辆已经占用，请更换车辆或者调整时间！',
    trafficExpenseApply_01:'交通接待申请报销详情不存在',
    trafficExpenseApply_02:'有发票金额和无发票金额必须小于总金额',
    askForLeave_01:'请假申请不存在',
    document_01: '文件不存在',
    docdetail_01: '条款不存在',
    docdetail_02: '条款编号已存在',
    docdetail_03: '存在未作答的条款，不能进行提交操作',
    docquestion_01: '问题不存在',
    docquestion_02: '答案不正确，请重新作答',
    docquestion_03: '请填写答案',
    docquestion_04: '答案正确',
    docquestion_05: '请回答完相关问题',
    documenttask_01: '文控任务没有分配审批人',
    documenttask_02: '已添加相关人员',
    documenttask_03: '请添加发布对象',
    documenttask_04: '请添加问题',
    kujiale_01: '清单生成中, 请稍后再尝试同步',
    kujiale_02: '请先选择户型',
    kujiale_03: '请在右上角设置中配置酷家乐关联账户',
    kujiale_04: '请选择酷家乐的标准户型',
    kujiale_05: '缺少关键参数',
    kujiale_06: '该用户已经绑定过酷家乐账号',
    kujiale_07: '该用户在酷家乐不存在',
    kujiale_08: '该邮箱在酷家乐不存在',
    kujiale_09: '该邮箱已与酷家乐其他用户绑定',
    kujiale_10: '该邮箱绑定产生了错误',
    askForLeavetask_01: '请假审批任务没有分配审批人',
    point_01: '积分不存在',
    signpdf_01: '订单不存在',
    signpdf_02: '签名失败',
    signpdf_03: '用户不存在',
    signpdf_04: '楼盘不存在',
    signpdf_05: '房间不存在',
    signpdf_06: '户型不存在',
    department_01: '部门不存在',
    department_02: '部门已存在',
    department_03: '只允许修改部门名称和部门编制',
    department_04: '层级为最高时，可以选择该部门',
    department_05: '层级不是最高',
    department_06: '上级部门应该为空',
    department_07: '选择部门不规范，请重新选择',
    department_08: '该部门下有岗位存在，不允许停用',
    position_01: '岗位不存在',
    position_02: '岗位已存在',
    position_03: '它是新添加的岗位的上级岗位',
    position_04: '部门或岗位不存在',
    position_05: '不可以选择本部门作为上级部门',
    styleTest_01: '此手机号码今天已提交过风格测试，请明天再来吧。',
    reimburserank_01: '报销职级不存在',
    reimburserank_02: '报销职级已存在',
    origin_01:'origin不存在',
    amortize_01: '待摊资产项目不存在',
    amortizebudget_01: '构建预算不存在',
    amortizesubscribe_01: '材料申购不存在',
    amortizesubscribe_02: '本次收料数量大于已采购数量',
    amortizesubscribe_03: '本次耗用数量大于现有数量',
    amortizecost_01: '构建费用不存在',
    amortizesubscribepurchase_01: '本次采购数量大于申购数量',

    amortize_32:'待摊资产项目新增审核任务没有分配审批人',
    amortize_33:'待摊资产构建预算审核任务没有分配审批人',
    amortize_34:'待摊资产材料申购审核任务没有分配审批人',
    amortize_35:'待摊资产材料收料审核任务没有分配审批人',
    amortize_36:'待摊资产人工结算审核任务没有分配审批人',
    amortize_37:'待摊资产材料耗用审核任务没有分配审批人',
    amortize_38:'待摊资产构建费用审核任务没有分配审批人',
    amortize_42:'待摊资产提交验收审核任务没有分配审批人',


    develop_01: '研发项目不存在',
    developbudget_01: '构建预算不存在',
    developsubscribe_01: '材料申购不存在',
    developsubscribe_02: '本次收料数量大于已采购数量',
    developsubscribe_03: '本次耗用数量大于现有数量',
    developcost_01: '构建费用不存在',
    developsubscribepurchase_01: '本次采购数量大于申购数量',

    develop_32:'研发项目新增审核任务没有分配审批人',
    develop_33:'研发构建预算审核任务没有分配审批人',
    develop_34:'研发材料申购审核任务没有分配审批人',
    develop_35:'研发材料收料审核任务没有分配审批人',
    develop_36:'研发人工结算审核任务没有分配审批人',
    develop_37:'研发材料耗用审核任务没有分配审批人',
    develop_38:'研发构建费用审核任务没有分配审批人',
    develop_42:'研发提交验收审核任务没有分配审批人',


    cashier_01:'出纳管理新增收款申报任务没有分配审批人',
    cashier_02:'出纳管理付款确认任务没有分配审批人',

    fixedassetspurch_01: '资产申购不存在',
    fixedassetspurch_02: '资产申购已存在',
    fixedassetspurch_03: '资产申购没有分配审批人',
    fixedassetspurch_04: '请增加固定资产',
    fixedassetspurch_05: '该申请单不允许此次操作',
    fixedassetscheck_01: '资产验收不存在',
    fixedassetscheck_02: '资产验收已存在',
    fixedassetscheck_03: '资产验收没有分配审批人',
    fixedassetscheck_04: '请增加验收项',
    fixedassetscheck_05: '请选择资产',
    fixedassetsrepair_01: '资产维修不存在',
    fixedassetsrepair_02: '资产维修已存在',
    fixedassetsrepair_03: '资产维修没有分配审批人',
    fixedassetsrepair_04: '请到详情页填写资产维修单后再完成任务',
    fixedassetsrepair_05: '该资产不允许此次操作',
    fixedassetsrepair_06: '请填写相关信息',
    fixedassetsscrap_01: '资产报废信息不存在',
    fixedassetsscrap_02: '资产报废信息已存在',
    fixedassetsscrap_03: '资产报废没有分配审批人',
    fixedassetsscrap_04: '该资产报废单不允许此次操作',
    fixedassetsscrap_05: '资产报废单已经存在',
    consumables_01:'部门不存在',
    consumables_02:'易耗品单不存在',
    consumables_03:'易耗品详情单不存在',
    takestock_01:'指派人不存在',
    takestock_02:'盘点单不存在',
    takestock_03:'盘点对象不存在',
    takestock_04:'盘点详情单不存在',
    takestock_05:'盘点对象已存在',
    takestock_06:'该订单已通过',
    corporateclients_01:'该企业客户已存在，请更换名称',
    template_01: '模板名称已经存在',
    template_02: '模板不存在',
    base_01: '数据类型已经存在',
    base_02: '数据名称不存在',
    base_03: '数据不存在',
    base_04: '顺序编码已存在',
    wechat_01: '未获取到手机号',
    wechat_02: '未获取到门店',

    project_34:'工程项目材料申购审核任务没有分配审批人',
    project_35:'工程项目材料收料审核任务没有分配审批人',
    project_36:'工程项目人工结算审核任务没有分配审批人',
    project_37:'工程项目材料耗用审核任务没有分配审批人',
    project_38:'工程项目构建费用审核任务没有分配审批人',
    project_42:'工程项目提交验收审核任务没有分配审批人',

    project_01: '研发项目不存在',
    projectbudget_01: '构建预算不存在',
    projectsubscribe_01: '材料申购不存在',
    projectsubscribe_02: '本次收料数量大于已采购数量',
    projectsubscribe_03: '本次耗用数量大于现有数量',
    projectcost_01: '构建费用不存在',
    projectsubscribepurchase_01: '本次采购数量大于申购数量',
};
